'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('../assets/editor/core.js');
function fixture(){const p=C.createProject(),a=C.createObject('rect',{id:'a',m:C.translate(50,70)}),b=C.createObject('text',{id:'b',text:'你好\n世界',m:C.translate(350,90)}),c=C.createObject('path',{id:'c',nodes:[{x:0,y:0,outX:60,outY:-80},{x:140,y:50,inX:80,inY:120}],m:C.translate(140,300)});p.objects.push(a,b,c);return p;}
const near=(a,b)=>a.forEach((n,i)=>assert.ok(Math.abs(n-b[i])<1e-8,`${n} != ${b[i]}`));

test('resizing mixed groups reflows text while preserving its rendered font size and shape',()=>{
 const p=C.createProject(),g=C.createObject('group',{id:'g',m:C.multiply(C.translate(50,60),C.around(0,0,1.2,1.2,20))}),t=C.createObject('text',{id:'t',parentId:'g',w:300,h:180,fontSize:32,m:C.translate(10,20)}),r=C.createObject('rect',{id:'r',parentId:'g'});
 p.objects=[g,t,r];const old=C.worldMatrix(p,t),before=C.clone(p),delta=C.around(0,0,2,.6),expected=C.multiply(delta,old);
 C.resizeObjects(p,['g'],delta);
 near(C.worldMatrix(p,t),[...old.slice(0,4),...expected.slice(4)]);
 assert.equal(t.fontSize,32);assert.ok(t.w>300);assert.ok(t.h<180);
 near(C.worldMatrix(p,r),C.multiply(delta,C.worldMatrix(before,before.objects[2])));
 assert.doesNotThrow(()=>C.validateProject(p));
 const reopened=C.validateProject(JSON.parse(JSON.stringify(p)));near(C.worldMatrix(reopened,reopened.objects[1]),C.worldMatrix(p,t));
});
test('project roundtrip preserves editable paths, text, effects and embedded resources',()=>{const p=fixture();p.objects[0].shadow.enabled=true;p.objects[2].glow.enabled=true;p.assets.img={id:'img',mime:'image/png',data:'data:image/png;base64,aGVsbG8=',name:'image'};p.objects.push(C.createObject('image',{assetId:'img',crop:{x:.1,y:.2,w:.7,h:.6}}));const q=C.validateProject(JSON.parse(JSON.stringify(p)));assert.deepEqual(q,p);q.objects[2].nodes[0].outX=72;assert.equal(C.validateProject(JSON.parse(JSON.stringify(q))).objects[2].nodes[0].outX,72);});
test('group and ungroup preserve world transforms after group rotation',()=>{const p=fixture(),g=C.group(p,['a','b']);C.transformObjects(p,[g],C.around(300,200,1.5,1.5,37));const before=p.objects.filter(o=>['a','b'].includes(o.id)).map(o=>C.worldMatrix(p,o));C.ungroup(p,g);p.objects.filter(o=>['a','b'].includes(o.id)).forEach((o,i)=>near(C.worldMatrix(p,o),before[i]));C.validateProject(p);});
test('nested group transforms, duplicate identities and resource references survive',()=>{const p=fixture(),g=C.group(p,['a','b']),h=C.group(p,[g,'c']);C.transformObjects(p,[h],C.translate(40,90));const ids=C.duplicate(p,[h]);assert.equal(ids.length,1);assert.equal(new Set(p.objects.map(o=>o.id)).size,p.objects.length);assert.equal(C.descendants(p,ids).size,5);C.validateProject(p);});
test('locked objects do not move and history restores exact data',()=>{const p=fixture();p.objects[0].locked=true;const old=C.clone(p),history=new C.History();history.push(p);C.transformObjects(p,['a','b'],C.translate(20,30));assert.deepEqual(p.objects[0],old.objects[0]);assert.notDeepEqual(p.objects[1],old.objects[1]);const undo=history.undo(p);assert.deepEqual(undo,old);assert.deepEqual(history.redo(undo),p);});
test('de Casteljau insertion preserves the cubic curve',()=>{const p=fixture(),o=p.objects[2],old=C.bounds(p,o);C.splitSegment(o,0);const after=C.bounds(p,o);assert.equal(o.nodes.length,3);near([old.x,old.y,old.w,old.h],[after.x,after.y,after.w,after.h]);assert.match(C.pathD(o),/ C /);});
test('alignment and distribution operate on visual bounds',()=>{const p=fixture();p.objects=p.objects.map((o,i)=>C.createObject('rect',{id:o.id,w:100,h:50,m:C.translate([0,70,400][i],i*100)}));C.distribute(p,['a','b','c'],'x');assert.equal(C.bounds(p,p.objects[1]).x,200);C.align(p,['a','b','c'],'top');assert.ok(p.objects.every(o=>C.bounds(p,o).y===0));});
test('snap aligns edges and supports equal spacing between neighbours',()=>{const p=C.createProject();p.canvas.width=2000;p.objects=[C.createObject('rect',{id:'a',w:100,h:100,m:C.translate(100,100)}),C.createObject('rect',{id:'b',w:100,h:100,m:C.translate(293,100)}),C.createObject('rect',{id:'c',w:100,h:100,m:C.translate(500,100)})];const guides=C.snap(p,['b'],10);assert.equal(C.bounds(p,p.objects[1]).x,300);assert.ok(guides.some(g=>g.spacing));});
test('rejects cycles, duplicates, bad resources, unsupported versions and matrices',()=>{for(const mutate of [p=>p.version=9,p=>p.objects[1].id='a',p=>p.objects[0].m=[0,0,0,0,0,0],p=>p.objects[0].parentId='missing',p=>p.objects[0].fill='url(https://example.org/x)',p=>{p.objects[0].type='group';p.objects[0].parentId='a';},p=>p.assets.x={id:'x',mime:'image/png',data:'https://example.org/img'}]){const p=fixture();mutate(p);assert.throws(()=>C.validateProject(p));}});
test('module regeneration retains manual transforms and user additions',()=>{const p=fixture(),module={id:'dots',version:1,generate:({params})=>[C.createObject('ellipse',{generatorKey:'dot',w:params.size})]};C.regenerate(p,module,{size:30,seed:1});const old=p.objects.at(-1);old.m=C.translate(99,88);old.editorState={keepRatio:false,sections:{fill:false,shadow:true}};const id=old.id;C.regenerate(p,module,{size:80,seed:1});const next=p.objects.at(-1);assert.equal(next.id,id);assert.deepEqual(next.m,C.translate(99,88));assert.equal(next.w,80);assert.deepEqual(next.editorState,old.editorState);assert.notEqual(next.editorState,old.editorState);assert.ok(p.objects.some(o=>o.id==='b'&&o.text==='你好\n世界'));});
test('ZIP output has correct signatures, entry counts and payloads',()=>{const bytes=C.zipStore([{name:'帧.png',data:new Uint8Array([1,2,3])},{name:'info.json',data:'{}'}]),view=new DataView(bytes.buffer);assert.equal(view.getUint32(0,true),0x04034b50);assert.equal(view.getUint32(bytes.length-22,true),0x06054b50);assert.equal(view.getUint16(bytes.length-14,true),2);assert.ok(bytes.includes(3));});
test('SVG keeps vector nodes, escapes text, crops images, includes effects',()=>{const ctx={PosterCore:C};ctx.globalThis=ctx;vm.runInNewContext(fs.readFileSync(require.resolve('../assets/editor/render.js'),'utf8'),ctx);const p=fixture();p.objects[0].shadow.enabled=true;p.objects[1].text='<script>&';p.objects[1].w=1000;const svg=ctx.PosterRender.svg(p);assert.match(svg,/<path d="M/);assert.match(svg,/<text /);assert.match(svg,/&lt;script&gt;&amp;/);assert.match(svg,/<feDropShadow/);assert.doesNotMatch(svg,/<script>/);});
