'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('../assets/editor/core.js');
const find=(p,id)=>p.objects.find(o=>o.id===id);
const near=(a,b)=>a.forEach((v,i)=>assert.ok(Math.abs(v-b[i])<1e-8,`${v} != ${b[i]}`));
function fixture(){const p=C.createProject();p.assets.img={id:'img',mime:'image/png',data:'data:image/png;base64,aGVsbG8='};p.objects=[C.createObject('path',{id:'shape',closed:true,fill:'none',nodes:[{x:0,y:0},{x:200,y:0},{x:60,y:150}],m:C.around(0,0,1.2,.8,13)}),C.createObject('image',{id:'image',assetId:'img',m:C.translate(20,30)})];return p;}
function renderer(){const ctx={PosterCore:C};ctx.globalThis=ctx;vm.runInNewContext(fs.readFileSync(require.resolve('../assets/editor/render.js'),'utf8'),ctx);return ctx.PosterRender;}
test('hiding the mask source hides clipped content and release never drops group effects silently',()=>{const p=fixture(),id=C.createClippingMask(p,['image']);find(p,'shape').visible=false;assert.equal(C.isVisible(p,find(p,'image')),false);assert.match(renderer().svg(p),/display="none"/);const S=require('../assets/editor/selection.js');assert.equal(S.matches(p,find(p,id),{x:-1000,y:-1000,w:3000,h:3000},true),false);find(p,'shape').visible=true;find(p,id).shadow.enabled=true;const before=C.clone(p);assert.throws(()=>C.releaseClippingMask(p,id),/投影/);assert.deepEqual(p,before);});
test('moving child across transformed parents preserves world geometry and sibling draw order',()=>{const p=fixture(),a=C.createLayer(p),b=C.createLayer(p),child=C.createLayer(p,a);find(p,a).m=C.around(0,0,1.8,.7,37);find(p,b).m=C.multiply(C.translate(230,180),C.around(0,0,.6,2,-21));C.moveLayer(p,'shape',child);const before=C.worldMatrix(p,find(p,'shape'));C.moveLayer(p,'shape',b);near(C.worldMatrix(p,find(p,'shape')),before);C.moveLayer(p,'image',b,'shape');assert.deepEqual(p.objects.filter(o=>o.parentId===b).map(o=>o.id),['image','shape']);C.moveLayer(p,'shape',null);near(C.worldMatrix(p,find(p,'shape')),before);C.validateProject(p);});
test('layer moves reject cycles, invalid parents and locked subtrees without mutation',()=>{const p=fixture(),a=C.createLayer(p),b=C.createLayer(p,a);C.moveLayer(p,'shape',b);for(const action of [()=>C.moveLayer(p,a,b),()=>C.moveLayer(p,'image','shape'),()=>C.moveLayer(p,'image',a,'shape')]){const before=C.clone(p);assert.throws(action);assert.deepEqual(p,before);}find(p,'shape').locked=true;const before=C.clone(p);assert.throws(()=>C.moveLayer(p,a,null),/解锁/);assert.deepEqual(p,before);assert.throws(()=>C.ungroup(p,b),/解锁/);find(p,a).locked=true;assert.throws(()=>C.moveLayer(p,'image',a),/解锁/);assert.throws(()=>C.createLayer(p,a),/解锁/);});
test('clipping mask creation uses adjacent lower shape and release preserves transformed content',()=>{const p=fixture(),before=p.objects.map(o=>C.worldMatrix(p,o)),id=C.createClippingMask(p,['image']),g=find(p,id);assert.equal(g.maskId,'shape');assert.equal(find(p,'image').parentId,id);p.objects.filter(o=>o.id!==id).forEach((o,i)=>near(C.worldMatrix(p,o),before[i]));C.transformObjects(p,[id],C.around(50,80,2,.5,29));const after=['shape','image'].map(k=>C.worldMatrix(p,find(p,k)));assert.deepEqual(C.releaseClippingMask(p,id),['shape','image']);['shape','image'].forEach((k,i)=>near(C.worldMatrix(p,find(p,k)),after[i]));assert.equal(find(p,id),undefined);C.validateProject(p);});
test('clipping masks reject unsuitable selection and preserve original project',()=>{for(const mutate of [p=>find(p,'shape').closed=false,p=>find(p,'shape').nodes.pop(),p=>find(p,'shape').locked=true,p=>p.objects.reverse(),p=>find(p,'shape').type='text']){const p=fixture();mutate(p);const before=C.clone(p);assert.throws(()=>C.createClippingMask(p,['shape','image']));assert.deepEqual(p,before);}const p=fixture();assert.throws(()=>C.createClippingMask(p,[]),/两个/);assert.throws(()=>C.createClippingMask(p,['shape']),/上方/);const id=C.createLayer(p);C.moveLayer(p,'shape',id);assert.throws(()=>C.createClippingMask(p,['shape','image']),/同一/);});
test('mask shape cannot leave its group or be deleted or regrouped before release',()=>{const p=fixture(),id=C.createClippingMask(p,['image']);p.objects.push(C.createObject('rect',{id:'extra',parentId:id}));for(const action of [()=>C.moveLayer(p,'shape',null),()=>C.remove(p,['shape']),()=>C.group(p,['shape','image']),()=>C.ungroup(p,id)]){const before=C.clone(p);assert.throws(action,/蒙版/);assert.deepEqual(p,before);}assert.equal(C.remove(p,[id]),4);assert.equal(p.objects.length,0);C.validateProject(p);});
test('mask copy remaps shape references and project round trip retains embedded editable content',()=>{const p=fixture(),id=C.createClippingMask(p,['shape','image']),copy=C.duplicate(p,[id])[0];assert.notEqual(find(p,copy).maskId,'shape');assert.equal(find(p,find(p,copy).maskId).parentId,copy);const restored=C.validateProject(JSON.parse(JSON.stringify(p)));assert.deepEqual(restored,p);assert.equal(restored.assets.img.data,p.assets.img.data);find(restored,'shape').nodes[1].x=170;assert.equal(C.validateProject(restored).objects.find(o=>o.id==='shape').nodes[1].x,170);});
test('validation upgrades legacy projects and rejects invalid mask targets',()=>{const legacy=fixture();legacy.version=1;assert.equal(C.validateProject(legacy).version,2);assert.equal(legacy.version,1);const p=fixture(),id=C.createClippingMask(p,['image']);for(const mutate of [q=>find(q,id).maskId='missing',q=>find(q,id).maskId='image',q=>find(q,'shape').parentId=null,q=>find(q,'shape').closed=false,q=>find(q,'image').maskId='shape']){const q=C.clone(p);mutate(q);assert.throws(()=>C.validateProject(q),/蒙版引用/);}});
test('SVG exports real transformed clipping geometry, embedded image and unique effect IDs',()=>{const p=fixture(),id=C.createClippingMask(p,['image']);C.duplicate(p,[id]);const svg=renderer().svg(p);assert.match(svg,/<clipPath id="mask-/);assert.match(svg,/clipPathUnits="userSpaceOnUse" transform="matrix\(/);assert.match(svg,/<path d="M /);assert.match(svg,/<image href="data:image\/png;base64,/);assert.doesNotMatch(svg,/data-object="shape"/);const ids=[...svg.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);assert.equal((svg.match(/<image /g)||[]).length,2);p.animation.enabled=true;p.animation.objectIds=['shape'];assert.notEqual(renderer().svg(p,0),renderer().svg(p,.5));});
test('regeneration cannot leave a dangling mask and remaps generated mask identities',()=>{const p=fixture();find(p,'shape').generatorModule='shape';find(p,'shape').generatorKey='clip';C.createClippingMask(p,['image']);const before=C.clone(p);assert.throws(()=>C.regenerate(p,{id:'shape',version:1,generate:()=>[]},{}),/蒙版引用/);assert.deepEqual(p,before);const q=C.createProject();let n=0;const module={id:'masker',version:1,generate:()=>{const key=String(++n);return[C.createObject('group',{id:'group'+key,generatorKey:'group',maskId:'mask'+key}),C.createObject('rect',{id:'mask'+key,parentId:'group'+key,generatorKey:'mask'}),C.createObject('ellipse',{id:'content'+key,parentId:'group'+key,generatorKey:'content'})];}};C.regenerate(q,module,{});const ids=q.objects.map(o=>o.id);C.regenerate(q,module,{});assert.deepEqual(q.objects.map(o=>o.id),ids);assert.equal(q.objects[0].maskId,ids[1]);C.validateProject(q);});
